name: Publish Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: ensures tags are fetched

      - name: Configure Git Credentials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install mkdocs-material and mike
        run: |
          python -m pip install --upgrade pip
          pip install --disable-pip-version-check -r requirements.txt


      - name: Extract version from tag
        run: |
            TAG_NAME=$(git tag --list "v*" --sort=-version:refname | head -n 1)
            echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
            echo "Extracted TAG_NAME: ${TAG_NAME}"

      - name: Deploy Docs for the Last 3 Tags
        run: |
            git checkout "$TAG_NAME"
            mike deploy "$TAG_NAME" --push
            mike set-default "$TAG_NAME" --push
